### PR TITLE
Remove mercury and metrics

### PR DESCRIPTION
**Pull request by TealNerd**

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by Maxopoly** [comment]
What's wrong with metrics

**Comment by ProgrammerDan** [comment]
repos down pretty often, causes weird intermediate build issues. I should rehost it in my build serv but lazy.

Does anyone actually _check_ the metrics stats for these plugins?

**Comment by Maxopoly** [comment]
Probably not, convinced.

Assuming this compiles, it should be good to merge.

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by DevotedServant** [comment]
Build finished.

**Comment by ProgrammerDan** [comment]
seems fine. Only thing really should be done is make a mention of 1.6.1 in the README that it's a hard fork w/ mercury removal. So any plugins that need mercury or call those functions that have been removed will break horribly unless you use the companion updates you've been working on.

There's already a list there of other hard forks, so it's a drop in.

**Pull request merged**
